[versions]
# -- Gradle --
android-compileSdk = "37"
android-minSdk = "29"
android-targetSdk = "37"

# -- Build Config & Plugins --
agp = "9.2.1"
kotlin = "2.4.0"
ksp = "2.3.9"

# -- KMP Core
composeMultiplatform = "1.11.1"

# -- Android Core --
coreKtx = "1.19.0"
lifecycle = "2.11.0"
activityCompose = "1.13.0"
kotlinxSerializationCore = "1.11.0"

# -- Compose & UI --
composeBom = "2026.06.00"
composeUiText = "1.11.3"
material3 = "1.5.0-alpha22"
adaptive = "1.2.0"
constraintLayout = "1.1.1"

# -- Navigation --
nav3Core = "1.1.3"
lifecycleNav3 = "2.11.0"
material3AdaptiveNav3 = "1.3.0-rc01"

# -- Accompanist --
accompanist = "0.37.3"

# -- DI --
koin = "4.2.2"
koinPlugin = "1.0.1"

# -- Data & Network --
datastore = "1.2.1"
room = "2.8.4"
sqlite = "2.7.0-rc01"
ktor = "3.5.0"

# -- Media --
media3 = "1.10.1"
coil = "3.5.0"
jellyfinFfmpeg = "1.9.0+1"

# -- Log --
napier = "2.7.1"

# -- ACRA --
acra = "5.13.1"

# -- Testing --
junit = "4.13.2"
kotest = "6.2.0"
mockwebserver = "5.4.0"
mockk = "1.14.11"
turbine = "1.2.1"
coroutinesTest = "1.11.0"
androidxTestExt = "1.3.0"
espresso = "3.7.0"
truth = "1.4.5"
coreTesting = "2.2.0"
kotlinStdlib = "2.4.0"
kotlinTest = "2.3.21"

[libraries]

# -- KMP Core --
components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "composeMultiplatform" }

# -- Android Core --
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.11.0" }

# -- Compose --
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "composeUiText" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }

# -- Kotlin --
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.8.0" }

# -- UI --
androidx-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version = "1.0.0" }

# -- Color --
material-kolor = { group = "com.materialkolor", name = "material-kolor", version = "4.1.1" }

# -- Navigation --
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-nav3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleNav3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

# -- Accompanist --
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# -- Media3 --
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose-material3", version.ref = "media3" }
jellyfin-ffmpeg = { group = "org.jellyfin.media3", name = "media3-ffmpeg-decoder", version.ref = "jellyfinFfmpeg" }

# -- Network --
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }

# -- Koin --
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit4 = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }

# -- Coil --
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# -- DataStore --
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
androidx-datastore-pref = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# -- Room --
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# -- Log
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }

# -- ACRA --
acra-core = { group = "ch.acra", name = "acra-core", version.ref = "acra" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }
acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }

# -- Test --
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest"}
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTesting" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koinPlugin" }
android-lint = { id = "com.android.lint", version.ref = "agp" }

[bundles]

# -- Shared --
shared-kotlin = [
    "kotlinx-serialization-json",
    "kotlinx-serialization-core",
    "kotlinx-datetime"
]
shared-network = [
    "ktor-core",
    "ktor-negotiation",
    "ktor-json"
]
shared-di = [
    "koin-core",
    "koin-annotations"
]
shared-image = [
    "coil-network-ktor",
]
shared-room = [
    "androidx-sqlite-bundled",
    "androidx-room-runtime",
    "androidx-room-ktx"
]
shared-datastore = [
    "androidx-datastore",
    "androidx-datastore-pref",
]
shared-tools = [
    "napier"
]

# -- Android --

android-core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-runtime-livedata",
]

android-network = [
    "ktor-okhttp",
    "ktor-android"
]

android-compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-ui-text",
    "androidx-material3",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-constraintlayout-compose",
    "androidx-activity-compose"
]

android-compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest"
]

android-ui = [
    "androidx-material-icons-core",
    "androidx-material3-adaptive",
    "androidx-palette",
    "material-kolor"
]

android-image = [
    "coil-video",
    "coil-compose",
]

android-navigation = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-lifecycle-viewmodel-nav3",
    "androidx-material3-adaptive-navigation3"
]

android-accompanist = [
    "accompanist-permissions"
]

android-player = [
    "androidx-media3-exoplayer",
    "androidx-media3-ui",
    "androidx-media3-ui-compose",
    "androidx-media3-session",
    "jellyfin-ffmpeg",
]

android-di = [
    "koin-android",
    "koin-compose",
    "koin-compose-viewmodel",
]

android-acra = [
    "acra-core",
    "acra-mail",
    "acra-dialog"
]

android-unit-test = [
    "junit",
    "kotest",
    "mockwebserver",
    "mockk",
    "koin-test",
    "koin-test-junit4",
    "turbine",
    "kotlinx-coroutines-test"
]

android-test = [
    "androidx-test-ext",
    "androidx-test-espresso",
    "truth",
    "androidx-core-testing",
    "mockk-android",
    "turbine",
    "koin-test"
]
