# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Release a beta debug version on Firebase"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
    release = firebase_app_distribution(
      app: "1:745123580180:android:1398ae6812f724e10eda01",
      groups: "testers",
    )
  end

end
