name: Android Beta CI

on:
  push:
    branches:
      - develop

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up Local Properties
        run: |
            echo "tmdb_token=${{ secrets.TMDB_TOKEN }}" > local.properties
            echo "firebase_beta_id=${{ secrets.FIREBASE_BETA_ID }}" >> local.properties

      - name: Decode Firebase Distribution services
        run: echo "${{ secrets.FIREBASE_DISTRIBUTION }}" | base64 --decode > firebase-distribution.json

      - name: Run Fastlane Beta
        run: |
            bundle exec fastlane test
            bundle exec fastlane beta