name: Android Beta CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up Local Properties
        run: |
            echo "tmdb_token=${{ secrets.TMDB_TOKEN }}" > local.properties
            echo "firebase_beta_id=${{ secrets.FIREBASE_BETA_ID }}" >> local.properties
            pwd

      #- name: Decode Google Services
      #  run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > app/google-services.json

      - name: Create Keystore Properties
        run: |
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
            echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" > keystore.properties
            echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
            echo "storeFile=keystore.jks" >> keystore.properties
            echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
            pwd

      - name: Run Fastlane Release
        run: |
          bundle exec fastlane test
          bundle exec fastlane release
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}